package org.noaidi.lopf

import java.nio.file.{Files, Path, Paths}
import scala.jdk.CollectionConverters.*
import org.noaidi.network.{CsvReader, Network, Schema, Topology}
import org.noaidi.prima.{PdhgParams, RowExpansion, SolveStatus}

/** Dispatch against PyPSA's own optimisation results.
  *
  * The target is `ac-dc-dispatch`, generated by solving the stock
  * `ac-dc-meshed` expansion problem and then fixing capacity at its optimum.
  * The stock example cannot be used directly: it is a capacity expansion
  * problem, so its objective is negative with a large `objective_constant`, and
  * fixing capacity at the *given* `p_nom` instead is infeasible — there is not
  * enough generation to serve the load.
  *
  * Objective, generator dispatch and line flows match PyPSA exactly. Nodal
  * prices match at 4 of 10 snapshots and are legitimately '''different''' at the
  * rest, which took some work to establish rather than assume:
  *
  *   - Fixing capacity at the expansion optimum makes the instance severely
  *     degenerate. Every line rating binds exactly, and at six snapshots every
  *     generator sits precisely at a bound with total output equal to total load
  *     — so there is no marginal generator and nothing pins the price.
  *   - Tightening the solver from 1e-9 to 1e-12 moves the price gap by exactly
  *     zero (3.874938 either way, with a dual residual of 0.0), which rules out
  *     non-convergence: this is a different vertex of the same optimal dual face,
  *     not an unfinished one.
  *   - Part of that freedom is the CO2 multiplier. The cap is tight here but
  *     weakly binding, so any multiplier in a range is optimal; PyPSA's simplex
  *     reports 0 and a first-order method lands near -0.99. Since gas emits
  *     0.24/0.35 per MWh that shifts every gas-attached bus price by 0.678 —
  *     exactly the residual observed at snapshot 9.
  *
  * So what is asserted of the dual is that it is '''valid''' — strong duality —
  * plus the one part of it that is forced rather than chosen: a generator
  * strictly inside its bounds pins its bus price in every optimal dual, by
  * complementary slackness. That check is independent of PyPSA and fails on a
  * real dual error, which asserting equality with one particular vertex would
  * not.
  *
  * `ac-dc-co2` exists because `ac-dc-dispatch` cannot test the CO2 constraint at
  * all: omitting it entirely reproduces that fixture's objective exactly. See
  * `ac_dc_co2` in the generator for why, and what had to change to make a cap
  * that bites.
  */
class LopfSuite extends munit.FunSuite:

  private def goldens: Path =
    Paths.get(sys.env.getOrElse("NOAIDI_GOLDENS", "reference/goldens"))

  private lazy val available: Boolean = Files.exists(goldens.resolve("schema.json"))
  private lazy val schema: Schema     = Schema.fromFile(goldens.resolve("schema.json"))

  private def network(name: String): Network =
    CsvReader.read(goldens.resolve("networks").resolve(name), schema, name)

  private def results(name: String): ujson.Value =
    ujson.read(Files.readString(goldens.resolve("results").resolve(s"$name.json")))

  private val params = PdhgParams(epsAbs = 1e-9, epsRel = 1e-9, maxIterations = 500_000)

  private val temporaries = scala.collection.mutable.ArrayBuffer.empty[Path]

  /** A copy of a golden network with one file rewritten.
    *
    * Routed through `CsvReader` rather than assembled in memory on purpose: a
    * hand-built table can express states the reader never produces, so a test
    * built that way can pass while the real path stays broken.
    */
  private def copyOf(name: String): Path =
    val dir = Files.createTempDirectory("noaidi-lopf-")
    temporaries += dir
    val source = goldens.resolve("networks").resolve(name)
    // Closed explicitly: `Files.list` is backed by an open directory handle, and
    // this runs once per mutation test.
    scala.util.Using.resource(Files.list(source)) { entries =>
      entries.iterator.asScala.foreach(f => Files.copy(f, dir.resolve(f.getFileName.toString)))
    }
    dir

  private def mutate(name: String, file: String, edit: String => String): Network =
    val dir    = copyOf(name)
    val target = dir.resolve(file)
    val before = Files.readString(target)
    val after  = edit(before)
    // Otherwise a fixture that silently stops matching turns into a test that
    // asserts something about an unmodified network.
    assertNotEquals(after, before, s"the edit to $file changed nothing")
    Files.writeString(target, after)
    CsvReader.read(dir, schema, name)

  private def withExtraFile(name: String, file: String, content: String): Network =
    val dir = copyOf(name)
    Files.writeString(dir.resolve(file), content)
    CsvReader.read(dir, schema, name)

  override def afterAll(): Unit =
    temporaries.foreach { dir =>
      if Files.exists(dir) then
        scala.util.Using.resource(Files.walk(dir)) { paths =>
          paths.sorted(java.util.Comparator.reverseOrder).forEach(Files.delete)
        }
    }

  /** A column of a golden frame, by entity name, with tagged NaN handled. */
  private def frameValue(frame: ujson.Value, row: Int, column: String): Double =
    val index = frame("columns").arr.indexWhere(_.str == column)
    assert(index >= 0, s"golden frame has no column '$column'")
    frame("values")(row)(index) match
      case ujson.Num(v) => v
      case o: ujson.Obj if o.value.contains("$nan") => Double.NaN
      case other => fail(s"unexpected golden value $other")

  test("the objective matches PyPSA's") {
    assume(available, "goldens missing — run reference/generate_goldens.py")
    val expected = results("ac-dc-dispatch")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val result = Lopf.solve(network("ac-dc-dispatch"), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(
      result.objective,
      target,
      1e-6 * math.max(1.0, math.abs(target)),
      s"objective ${result.objective} against PyPSA's $target",
    )
  }

  test("generator dispatch matches PyPSA's") {
    assume(available, "goldens missing")
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("generator_p")
    val result   = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal)

    // Absolute, in MW: an idle generator sits at zero and a relative tolerance
    // would mean nothing there.
    n.snapshots.indices.foreach { t =>
      n.require("Generator").ids.foreach { g =>
        assertEqualsDouble(
          result.dispatch("Generator", g, t),
          frameValue(expected, t, g),
          1e-3,
          s"snapshot $t, generator $g",
        )
      }
    }
  }

  test("total generation matches total load at every snapshot") {
    assume(available, "goldens missing")
    // The invariant bus balance exists to enforce, checked globally so a sign
    // error that cancels within one bus still shows up.
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val loads  = n.require("Load")

    n.snapshots.indices.foreach { t =>
      val generated = n.require("Generator").ids.map(result.dispatch("Generator", _, t)).sum
      val demanded  = loads.ids.map(loads.valueAt("p_set", _, t)).sum
      // Links convert with an efficiency, so the two sides differ by conversion
      // loss; ac-dc-dispatch's links are lossless, which this relies on.
      assertEqualsDouble(generated, demanded, 1e-3, s"snapshot $t")
    }
  }

  test("line flows stay within their ratings") {
    assume(available, "goldens missing")
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val lines  = n.require("Line")

    n.snapshots.indices.foreach { t =>
      lines.ids.foreach { l =>
        val flow = result.dispatch("Line", l, t)
        val rating = lines.float("s_nom", l)
        assert(
          math.abs(flow) <= rating + 1e-6,
          s"snapshot $t, line $l: flow $flow exceeds rating $rating",
        )
      }
    }
  }

  test("line flows match PyPSA's") {
    assume(available, "goldens missing")
    // This is what the cycle constraints buy. Bus balance alone leaves the flow
    // pattern around a cycle underdetermined, so before they existed this test
    // asserted the *disagreement* — and its failure was the signal to write this.
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("line_p0")
    val result   = Lopf.solve(n, params)

    n.snapshots.indices.foreach { t =>
      n.require("Line").ids.foreach { l =>
        assertEqualsDouble(
          result.dispatch("Line", l, t),
          frameValue(expected, t, l),
          1e-3,
          s"snapshot $t, line $l",
        )
      }
    }
  }

  test("the cycle basis has the circuit rank of the passive graph") {
    assume(available, "goldens missing")
    // edges - nodes + components, counted over passive branches only. The
    // reference network is two triangles plus a lone pair, so two cycles.
    val n      = network("ac-dc-dispatch")
    val cycles = Cycles.basis(n)
    val edges  = Topology.passiveBranches(n).size
    val nodes  = n.require("Bus").ids.count(b => Topology.passiveBranches(n).exists((a, c) => a == b || c == b))
    val comps  = Topology.subNetworks(n).count(_.size > 1)
    assertEquals(cycles.size, edges - nodes + comps, s"cycles=${cycles.map(_.terms)}")
    assertEquals(cycles.size, 2)
  }

  test("an annuitised overnight cost is refused rather than read as a per-unit one") {
    assume(available, "goldens missing")
    // PyPSA annuitises `overnight_cost` over `lifetime` at `discount_rate` and
    // scales by the modelled horizon. Reading it as `capital_cost` is wrong by
    // the annuity factor -- about tenfold on a 25-year asset -- and, since its
    // default is NaN rather than zero, it cannot be handled by falling back.
    val n = mutate(
      "ac-dc-meshed",
      "generators.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",overnight_cost") :: lines.tail.map(_ + ",1000.0") mkString "\n"
      },
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(n, params))
    assert(failure.getMessage.contains("overnight_cost"), failure.getMessage)
  }

  test("a modular capacity is refused rather than solved continuously") {
    assume(available, "goldens missing")
    // `p_nom_mod` makes capacity an integer number of blocks, which is a
    // mixed-integer problem. Solved continuously it returns 3.7 blocks reporting
    // `Optimal`.
    val n = mutate(
      "ac-dc-meshed",
      "generators.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",p_nom_mod") :: lines.tail.map(_ + ",100.0") mkString "\n"
      },
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(n, params))
    assert(failure.getMessage.contains("p_nom_mod"), failure.getMessage)
  }

  // The two stock expansion examples, which between them are why this exists:
  // `ac-dc-meshed` is the brief's starting network and `storage-hvdc` couples
  // expansion to storage. Both were rejected until now.
  Seq("ac-dc-meshed", "storage-hvdc").foreach { name =>
    test(s"capacity expansion matches PyPSA's objective and chosen capacities on $name") {
      assume(available, "goldens missing")
      val expected = results(name)("optimize")
      assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

      val n      = network(name)
      val result = Lopf.solve(n, params)
      assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

      // All three numbers, because they differ by 21.9 million on `ac-dc-meshed`
      // and reporting the wrong one would still look plausible. PyPSA's
      // `objective` is the cost of the *change*: capital cost on the whole
      // optimal capacity, minus the capital cost of what the network came with.
      val target = expected("objective").num
      assertEqualsDouble(result.objective, target, 1e-6 * math.abs(target), s"objective, PyPSA's $target")

      val constant = expected("objective_constant").num
      assertEqualsDouble(
        result.totalSystemCost - result.objective,
        constant,
        1e-6 * math.abs(constant),
        s"objective_constant, PyPSA's $constant",
      )
      assertEqualsDouble(
        result.totalSystemCost,
        expected("total_system_cost").num,
        1e-6 * math.abs(expected("total_system_cost").num),
        "total system cost",
      )

      // And the capacities themselves, which are the answer an expansion problem
      // is asked for. Matching the objective without them would leave a wrong
      // build-out that happens to cost the right amount undetected.
      val capacities = expected("nominal_opt").obj
      var compared   = 0
      capacities.foreach { (component, chosen) =>
        n.table(component).foreach { table =>
          chosen.obj.foreach { (id, value) =>
            assertEqualsDouble(
              result.capacity(component, id),
              value.num,
              1e-4 * math.max(1.0, math.abs(value.num)),
              s"$component '$id' capacity",
            )
            compared += 1
          }
        }
      }
      assert(compared > 10, s"only $compared capacities compared on $name")

      // Not vacuous: something really was expanded away from what the file said.
      val moved = capacities.exists { (component, chosen) =>
        n.table(component).exists { table =>
          chosen.obj.exists { (id, value) =>
            table.has(id) &&
            math.abs(value.num - table.float(Expansion.nominalAttribute(component), id)) > 1.0
          }
        }
      }
      assert(moved, s"$name's optimum equals its given capacity everywhere, so nothing was expanded")
    }
  }

  test("stores match PyPSA's energy, power and chosen capacity") {
    assume(available, "goldens missing")
    // A Store is not a StorageUnit renamed: one signed power variable rather
    // than four, no efficiencies, and -- the part most likely to be got wrong --
    // no power rating at all. Both frames are compared, because a sign error on
    // `p` gives a store that charges when it should discharge while still
    // balancing every bus at every snapshot.
    val expected = results("store-bank")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val n      = network("store-bank")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * math.abs(target), s"against PyPSA's $target")

    val stores = n.require("Store")
    Seq[(String, (String, Int) => Double)](
      "store_e" -> result.energy,
      "store_p" -> ((id, t) => result.dispatch("Store", id, t)),
    ).foreach { (frame, read) =>
      n.snapshots.indices.foreach { t =>
        stores.ids.foreach { id =>
          assertEqualsDouble(read(id, t), frameValue(expected(frame), t, id), 1e-4, s"$frame, $id at $t")
        }
      }
    }

    // The extendable store's capacity, which is what ties Stores to the
    // expansion machinery -- `e_nom` is an energy where every other component's
    // nominal attribute is a power.
    stores.ids.foreach { id =>
      assertEqualsDouble(
        result.capacity("Store", id),
        expected("nominal_opt")("Store")(id).num,
        1e-4,
        s"Store '$id' capacity",
      )
    }
  }

  test("the store fixture's features are load-bearing, not merely present") {
    assume(available, "goldens missing")
    // Guarding the guard, as for `storage-cycle`. Each of these took a reshaped
    // fixture to achieve, and each would let an implementation that ignored the
    // feature pass the comparison above.
    val expected = results("store-bank")("optimize")
    val e        = expected("store_e")
    val last     = network("store-bank").snapshots.length - 1

    // Cyclic: `swing` ends the horizon holding energy and discharges it at the
    // first snapshot, which a non-cyclic store starting from zero cannot do.
    assert(frameValue(e, last, "swing") > 1.0, "the cyclic store ends empty, so its wrap carries nothing")
    assert(
      frameValue(expected("store_p"), 0, "swing") > 1.0,
      "the cyclic store does not discharge at the first snapshot, so the wrap is unobservable",
    )

    // Both ends of `tank`'s band, which is `[e_min_pu, e_max_pu] · e_nom` and
    // not `[0, e_nom]` -- 20 and 100 against a nominal 200.
    val levels = (0 to last).map(frameValue(e, _, "tank"))
    assertEqualsDouble(levels.min, 20.0, 1e-3, "the lower band never binds")
    assertEqualsDouble(levels.max, 100.0, 1e-3, "the upper band never binds")

    // And the extendable store is built to exactly its ceiling, so the capacity
    // variable's own upper bound binds too.
    assertEqualsDouble(expected("nominal_opt")("Store")("grow").num, 60.0, 1e-3, "e_nom_max")
  }

  test("a store has no power rating, unlike a storage unit") {
    assume(available, "goldens missing")
    // PyPSA generates no operational bound for `Store-p`, so a store's rate
    // follows only from its energy band and the elapsed hours. Bounding `p` by
    // `e_nom` is the obvious reading and is strictly tighter -- and it would be
    // invisible unless some store actually moves more than its nominal energy in
    // one snapshot. `tank` does: 35 MW over 2 hours against an `e_nom` of 200 is
    // not enough, so this asserts the bound is absent rather than slack.
    val model = Lopf.build(network("store-bank"))
    val n     = network("store-bank")
    n.require("Store").ids.foreach { id =>
      n.snapshots.indices.foreach { t =>
        val column = model.map.column(Stores.Power, id, t)
        assert(
          model.problem.variableLower(column).isNegInfinity &&
            model.problem.variableUpper(column).isPosInfinity,
          s"Store '$id' power at snapshot $t is bounded " +
            s"[${model.problem.variableLower(column)}, ${model.problem.variableUpper(column)}]",
        )
      }
    }
  }

  test("a capacity floor above its ceiling is refused rather than solved empty") {
    assume(available, "goldens missing")
    // `p_nom_min > p_nom_max` makes the capacity variable's own interval empty.
    // The builder would refuse it too, but with a message about a variable index
    // rather than about a generator.
    val n = mutate(
      "ac-dc-meshed",
      "generators.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",p_nom_min,p_nom_max") :: lines.tail.map(_ + ",500.0,100.0") mkString "\n"
      },
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(n, params))
    assert(failure.getMessage.contains("p_nom_min"), failure.getMessage)
  }

  test("a NaN capacity floor is refused, which is what the negativity guard is for") {
    assume(available, "goldens missing")
    // The guard is written `!(minimum >= 0.0)` rather than `minimum < 0.0`
    // precisely so a NaN fires it -- every comparison against NaN is false, so
    // the natural spelling would let it through and produce a capacity variable
    // with a NaN bound. Worth pinning because the two spellings look equivalent.
    val n = mutate(
      "ac-dc-meshed",
      "generators.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",p_nom_min") :: lines.tail.map(_ + ",nan") mkString "\n"
      },
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(n, params))
    assert(failure.getMessage.contains("p_nom_min"), failure.getMessage)
  }

  test("a security-constrained solve refuses an extendable network") {
    assume(available, "goldens missing")
    // The guard `Lopf.build`'s blanket extendable rejection used to provide for
    // free. The security rows cap post-contingency flow at the rating in the
    // file while an extendable branch's pre-contingency flow is bounded by a
    // capacity variable, so where the optimum shrinks a line below its given
    // rating -- which is what happens on `ac-dc-meshed` -- the contingency limit
    // is looser than the network being built can carry.
    val failure = intercept[Sclopf.UnsupportedNetwork] {
      Sclopf.build(network("ac-dc-meshed"), Some(IndexedSeq(Sclopf.Outage("Line", "0"))))
    }
    assert(failure.getMessage.contains("extendable"), failure.getMessage)
  }

  test("an extendable network with cycles builds rows Sclopf's copy could index") {
    assume(available, "goldens missing")
    // The row-ordering invariant, asserted directly rather than through the
    // solver. `LpBuilder.build` hoists every equality to the front, so an
    // inequality emitted between two equality blocks shifts the later ones and
    // breaks the one-for-one row copy `Sclopf` performs. Emitting the capacity
    // rows in the middle did exactly that on every extendable network with a
    // cycle.
    val model = Lopf.build(network("ac-dc-meshed"))
    (0 until model.translation.numOriginalRows).foreach { r =>
      val mapped = model.translation.expansionOf(r) match
        case RowExpansion.Direct(row)  => row
        case RowExpansion.Negated(row) => row
        case other                     => fail(s"row $r expanded to $other")
      assertEquals(mapped, r, s"original row $r moved to standard-form row $mapped")
    }
  }

  test("storage dispatch, state of charge and spill match PyPSA's") {
    assume(available, "goldens missing")
    // The whole storage model against PyPSA, cell by cell. All five frames are
    // compared and not just the net injection: `p = p_dispatch - p_store`, so an
    // implementation with the two efficiencies transposed can reproduce every
    // bus balance exactly and still hold a different amount of energy at every
    // snapshot.
    val expected = results("storage-cycle")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val n      = network("storage-cycle")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * target, s"against PyPSA's $target")

    val units = n.require("StorageUnit")
    val frames = Seq[(String, (String, Int) => Double)](
      "storage_state_of_charge" -> result.stateOfCharge,
      "storage_p_dispatch"      -> result.discharging,
      "storage_p_store"         -> result.charging,
      "storage_spill"           -> result.spill,
      "storage_p"               -> ((id, t) => result.dispatch("StorageUnit", id, t)),
    )

    frames.foreach { (name, read) =>
      val frame = expected(name)
      n.snapshots.indices.foreach { t =>
        units.ids.foreach { id =>
          assertEqualsDouble(read(id, t), frameValue(frame, t, id), 1e-4, s"$name, $id at snapshot $t")
        }
      }
    }
  }

  test("the fixture's storage flags are load-bearing, not merely present") {
    assume(available, "goldens missing")
    // Guarding the guard. Each of these could be set in the fixture and change
    // nothing about the answer, in which case the comparison above would pass
    // for an implementation that ignored the flag entirely. The first attempt at
    // this fixture had exactly that problem twice over -- every spill came out
    // zero, and the cyclic unit ended its horizon empty, which makes its wrap
    // indistinguishable from a non-cyclic unit starting from zero.
    val expected = results("storage-cycle")("optimize")
    val soc      = expected("storage_state_of_charge")
    val spill    = expected("storage_spill")
    val last     = network("storage-cycle").snapshots.length - 1

    // Cyclic: the unit ends holding energy, and that energy is what it starts
    // with. Under a non-cyclic reading it would begin at zero and could not
    // discharge at the first snapshot, which it does.
    val endsCharged = frameValue(soc, last, "cyclic")
    assert(endsCharged > 1.0, s"the cyclic unit ends at $endsCharged, so its wrap carries nothing")
    assertEqualsDouble(
      frameValue(expected("storage_p_dispatch"), 0, "cyclic"),
      34.0,
      1e-3,
      "the cyclic unit does not discharge at the first snapshot, so the wrap is not observable",
    )

    // Spill: forced, not optional. Inflow arrives faster than the unit can hold
    // or discharge it.
    val spilled = (0 to last).map(frameValue(spill, _, "hydro")).max
    assert(spilled > 1.0, s"no spill anywhere ($spilled), so the spill variable is untested")
  }

  test("scigrid-de solves at scale, which storage is what unblocked") {
    assume(available, "goldens missing")
    // 60,552 variables and 23,688 rows: two orders of magnitude past every other
    // fixture, and the first realistic network this module has been able to
    // build at all. Storage was the only thing blocking it -- it has no
    // extendable component, no committable generator and no global constraint.
    //
    // Solved at 1e-4 rather than the suite's 1e-9, and that is a real limitation
    // rather than a convenience. Prima reaches 1e-4 in 14,848 iterations and
    // about 13 s here; reaching 1e-6 takes 281,792 iterations and about 145 s,
    // which is too slow to run on every commit. It does converge -- 100,000
    // iterations leaves it at 4.06e-06 relative, 200,000 at 1.29e-06 -- so this
    // is a first-order method being slow on a large problem, not a stall. NOTES
    // records the progression.
    //
    // Only the objective is asserted. The dispatch cannot be: PyPSA's own
    // Kirchhoff cycle basis differs between runs, and the two optima it reaches
    // differ by up to 750 MW at individual generators for the same cost. The
    // golden says so in a `dispatch_note` beside those frames.
    val expected = results("scigrid-de")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")
    assert(
      expected.obj.contains("dispatch_note"),
      "the golden no longer warns that this network's dispatch is degenerate",
    )

    val n     = network("scigrid-de")
    val model = Lopf.build(n)
    assert(model.problem.numVariables > 50_000, s"only ${model.problem.numVariables} variables")

    val loose  = PdhgParams(epsAbs = 1e-4, epsRel = 1e-4, maxIterations = 100_000)
    val result = Lopf.solve(n, loose)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 2e-4 * math.abs(target), s"against PyPSA's $target")
  }

  test("a state-of-charge set point is honoured, and it changes the answer") {
    assume(available, "goldens missing")
    // Built rather than refused, because `storage-hvdc` carries two of them and
    // dropping a fixing constraint leaves the trajectory free -- a strictly
    // cheaper problem returning `Optimal`, which is the worst shape of wrong
    // answer. They bind there: deleting them moves that fixture's objective from
    // 14,670,509 to 14,661,496.
    //
    // Asserted here as well, on a fixture where the effect is large enough to
    // read, and pinned across every snapshot rather than one.
    val pinned = 90.0
    val n = mutate(
      "storage-cycle",
      "storage_units.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",state_of_charge_set") ::
          lines.tail.map(row => row + (if row.startsWith("battery,") then s",$pinned" else ",")) mkString "\n"
      },
    )
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    n.snapshots.indices.foreach { t =>
      assertEqualsDouble(result.stateOfCharge("battery", t), pinned, 1e-4, s"battery at snapshot $t")
    }
    // The other units are untouched -- a blank cell means "not set", not zero.
    val free = n.snapshots.indices.map(result.stateOfCharge("cyclic", _)).max
    assert(free > 1.0, s"the unset unit was pinned too (max soc $free)")

    // And the constraint is not free: pinning costs more than the unconstrained
    // optimum, which is what says it was actually imposed.
    val unconstrained = Lopf.solve(network("storage-cycle"), params).objective
    assert(
      result.objective > unconstrained + 1.0,
      s"pinning the state of charge changed nothing (${result.objective} against $unconstrained)",
    )
  }

  test("a storage power set point is still refused") {
    assume(available, "goldens missing")
    // `p_set` fixes the *net* `p_dispatch - p_store` while `p_dispatch_set` and
    // `p_store_set` fix them individually -- three different constraints, none
    // used by any golden here.
    val n = mutate(
      "storage-cycle",
      "storage_units.csv",
      text => {
        val lines = text.linesIterator.toList
        (lines.head + ",p_set") :: lines.tail.map(_ + ",10.0") mkString "\n"
      },
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(n, params))
    assert(failure.getMessage.contains("p_set"), failure.getMessage)
  }

  test("the dual solution is optimal, though not the same one PyPSA reports") {
    assume(available, "goldens missing")
    // Prices come off the balance-constraint duals through RowTranslation. The
    // primal matches PyPSA exactly -- objective, dispatch and flows -- so the
    // dual question is only *which* optimal dual, and on this fixture that is not
    // unique.
    //
    // The instance is deliberately degenerate: capacity was sized from the
    // expansion optimum, so every line rating binds exactly, and every gas
    // generator sits at its zero lower bound. Far more constraints are active at
    // the optimum than there are variables, which makes the optimal dual a face
    // rather than a point. PyPSA's simplex reports a vertex of it (prices equal
    // to the marginal wind costs); a first-order method converges to a different
    // point of the same face.
    //
    // So what is asserted here is strong duality -- the two objectives agreeing
    // is what makes both the primal and the dual optimal rather than merely
    // feasible -- plus finiteness of every price. The part of the dual that is
    // *forced* rather than chosen is asserted separately, in "a generator
    // strictly inside its bounds pins its bus price"; between them those two
    // cover what any optimal dual must satisfy. Asserting equality with PyPSA's
    // prices would be asserting a choice neither solver is obliged to make.
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal)

    // Strong duality: the two objectives agreeing is what makes both the primal
    // and the dual optimal rather than merely feasible.
    assertEqualsDouble(
      result.solution.objectiveValue,
      result.solution.dualObjectiveValue,
      1e-6 * math.max(1.0, math.abs(result.objective)),
      s"strong duality violated: ${result.solution.kkt}",
    )

    // And every price is a finite number, so the dual path cannot silently be
    // NaN -- which is the failure that would otherwise hide behind a tolerance.
    n.require("Bus").ids.foreach { bus =>
      n.snapshots.indices.foreach { t =>
        assert(result.marginalPrice(bus, t).isFinite, s"bus $bus at snapshot $t")
      }
    }
  }

  test("the objective matches PyPSA's when a CO2 cap binds") {
    assume(available, "goldens missing")
    // ac-dc-co2 prices gas below wind so the cap displaces generation it would
    // otherwise be economic to run. Ignoring the constraint gives 2819.52 against
    // this 3178.55, so unlike ac-dc-dispatch this fixture can tell an
    // implementation of the constraint apart from its absence.
    val expected = results("ac-dc-co2")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val result = Lopf.solve(network("ac-dc-co2"), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * math.abs(target), s"against PyPSA's $target")

    // And PyPSA agrees the cap is doing work, so this is not a fixture that
    // happens to be satisfied for some other reason.
    assertNotEquals(expected("global_constraint_mu")("co2_limit").num, 0.0)
  }

  test("the CO2 cap is respected and reached") {
    assume(available, "goldens missing")
    // Both halves matter. Emissions above the cap mean the row is absent or
    // mis-signed; emissions well *under* it would mean the row is over-tight, and
    // the objective comparison alone cannot separate those from a coefficient
    // error that happens to land on the same cost.
    val n        = network("ac-dc-co2")
    val result   = Lopf.solve(n, params)
    val gens     = n.require("Generator")
    val carriers = n.require("Carrier")

    val emitted = n.snapshots.indices.map { t =>
      gens.ids.map { g =>
        val intensity = carriers.float("co2_emissions", gens.string("carrier", g))
        // The `generators` weighting, which is what PyPSA scales emissions by --
        // not `objective`, which scales cost. Reading the same column the builder
        // reads would make this agree with the implementation rather than check
        // it, so it is named here independently.
        result.dispatch("Generator", g, t) * intensity / gens.valueAt("efficiency", g, t) *
          n.weighting("generators", t)
      }.sum
    }.sum

    val cap = n.require("GlobalConstraint").float("constant", "co2_limit")
    assert(emitted <= cap + 1e-3, s"emitted $emitted exceeds cap $cap")
    // Unconstrained this network emits 6702, so landing on the cap is the
    // constraint binding rather than an accident of the dispatch.
    assertEqualsDouble(emitted, cap, 1e-2, s"emitted $emitted against cap $cap")
  }

  test("a generator strictly inside its bounds pins its bus price") {
    assume(available, "goldens missing")
    // The part of the dual that is forced rather than chosen. Complementary
    // slackness makes an interior variable's reduced cost zero in *every* optimal
    // dual, so for a zero-emission generator — where the CO2 term vanishes and no
    // other row touches it — the bus price equals its marginal cost exactly.
    // Unlike a comparison against PyPSA's vertex this cannot be failed by a
    // legitimate alternative optimum, and it is what actually separates a dual bug
    // from degeneracy on this fixture: it is how snapshot 9 was identified as the
    // former while 6 and 8 were the latter.
    val n        = network("ac-dc-dispatch")
    val result   = Lopf.solve(n, params)
    val gens     = n.require("Generator")
    val carriers = n.require("Carrier")
    var checked  = 0

    n.snapshots.indices.foreach { t =>
      gens.ids.foreach { g =>
        val pNom  = gens.float("p_nom", g)
        val lo    = pNom * gens.valueAt("p_min_pu", g, t)
        val hi    = pNom * gens.valueAt("p_max_pu", g, t)
        val p     = result.dispatch("Generator", g, t)
        val clean = carriers.float("co2_emissions", gens.string("carrier", g)) == 0.0
        // A margin well above the solver tolerance, so "interior" is not a
        // rounding artefact of a variable resting on its bound.
        if clean && p > lo + 1e-2 && p < hi - 1e-2 then
          checked += 1
          assertEqualsDouble(
            result.marginalPrice(gens.string("bus", g), t),
            gens.valueAt("marginal_cost", g, t),
            1e-3,
            s"snapshot $t, interior generator $g",
          )
      }
    }
    // Otherwise the test passes by finding nothing to check.
    assert(checked >= 2, s"only $checked interior generator(s) found; the check is vacuous")
  }

  test("a component attached to a nonexistent bus is rejected") {
    assume(available, "goldens missing")
    // Not hypothetical: a load whose bus is stale simply vanishes from the balance
    // rows, and the LP stays feasible and returns a *cheaper* answer with no
    // diagnostic. Cheaper-and-silent is the worst direction for an error to go.
    val broken  = mutate("ac-dc-dispatch", "loads.csv", _.replace(",Manchester,", ",Mancester,"))
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(broken, params))
    assert(failure.getMessage.contains("Mancester"), failure.getMessage)
  }

  test("an unmodelled component is rejected rather than dropped") {
    assume(available, "goldens missing")
    // A ShuntImpedance draws real power and is not built here. Dropping it leaves
    // a feasible LP describing a different network, so it has to be refused — the
    // same reason extendable capacity and storage are.
    val broken = withExtraFile(
      "ac-dc-dispatch",
      "shunt_impedances.csv",
      "name,bus,g,b\nshunt,Manchester,0.1,0.0\n",
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(broken, params))
    assert(failure.getMessage.contains("ShuntImpedance"), failure.getMessage)
  }

  // A test asserting that prices lie between the cheapest and dearest marginal
  // cost was written here and removed: the claim is false. With a binding
  // transmission limit, serving one more MW at a bus can require raising
  // expensive generation at one end while backing off cheap generation at the
  // other, and the resulting nodal price legitimately exceeds every generator's
  // cost. Congestion rent is a feature of locational pricing, not a symptom. The
  // observed 6.80 against a dearest cost of 5.89 is within that.
  //
  // What remains open is the gap against PyPSA, recorded in NOTES rather than
  // papered over with a tolerance.

  test("a cycle spanning transformers matches PyPSA's dispatch") {
    assume(available, "goldens missing")
    // The LOPF half of the transformer conversion. `Cycles.impedance` refers a
    // transformer to `s_nom` and `tap_ratio` where a line goes to `v_nom^2`, and
    // this fixture has a cycle crossing two transformers so the choice changes
    // the flows -- in a radial network topology would fix them and any base would
    // do.
    val expected = results("transformer-levels")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val n      = network("transformer-levels")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * target, s"against PyPSA's $target")

    val flows = expected("transformer_p0")
    n.snapshots.indices.foreach { t =>
      n.require("Transformer").ids.foreach { id =>
        assertEqualsDouble(
          result.dispatch("Transformer", id, t),
          frameValue(flows, t, id),
          1e-3,
          s"snapshot $t, transformer $id",
        )
      }
    }
  }

  test("a network whose impedance comes only from type names matches PyPSA's dispatch") {
    assume(available, "goldens missing")
    // Every branch in `standard-types` is typed, so the LP's Kirchhoff rows are
    // built entirely out of values that appear nowhere in the network's files.
    // Both cycles matter: the 380 kV triangle fixes the line expansion and the
    // loop through both transformers fixes the transformer one, and neither is
    // radial, so topology alone does not determine the split.
    val expected = results("standard-types")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val n      = network("standard-types")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * target, s"against PyPSA's $target")

    Seq("Line" -> expected("line_p0"), "Transformer" -> expected("transformer_p0")).foreach {
      (component, frame) =>
        n.snapshots.indices.foreach { t =>
          n.require(component).ids.foreach { id =>
            assertEqualsDouble(
              result.dispatch(component, id, t),
              frameValue(frame, t, id),
              1e-3,
              s"snapshot $t, $component $id",
            )
          }
        }
    }
  }

  test("a security-constrained solve expands types before computing outage factors") {
    assume(available, "goldens missing")
    // `Sclopf.build` has to expand before it reaches `Lodf`, not merely rely on
    // `Lopf.build` doing it: the outage factors are computed from susceptance,
    // so an unexpanded network would give the dispatch model the right
    // impedances and the contingency rows `x = 0`.
    //
    // Exercised through `build` rather than `solve`, which is the whole point.
    // `Sclopf.solve` expands on its own way in, so a test that only called it
    // would pass with `build` left unexpanded -- which is exactly what happened
    // on the first attempt at this test.
    //
    // Outages are named rather than defaulted: both transformers and the 110 kV
    // line are bridges here, and outaging a bridge has no defined
    // post-contingency flow.
    val n = network("standard-types")
    val outages =
      IndexedSeq(Sclopf.Outage("Line", "hv12"), Sclopf.Outage("Line", "hv23"), Sclopf.Outage("Line", "hv31"))

    val model  = Sclopf.build(n, Some(outages))
    val plain  = Lopf.build(n)
    assert(
      model.problem.numConstraints > plain.problem.numConstraints,
      "no contingency rows were added, so the factors were never built",
    )

    val result = Sclopf.solve(n, Some(outages), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")
    assert(
      result.objective >= Lopf.solve(n, params).objective - 1e-6,
      "a secure dispatch cannot cost less than an unconstrained one",
    )
  }
