package org.noaidi.lopf

import java.nio.file.{Files, Path, Paths}
import org.noaidi.network.{CsvReader, Network, Schema}
import org.noaidi.prima.{PdhgParams, SolveStatus}

/** Dispatch against PyPSA's own optimisation results.
  *
  * The target is `ac-dc-dispatch`, generated by solving the stock
  * `ac-dc-meshed` expansion problem and then fixing capacity at its optimum.
  * The stock example cannot be used directly: it is a capacity expansion
  * problem, so its objective is negative with a large `objective_constant`, and
  * fixing capacity at the *given* `p_nom` instead is infeasible — there is not
  * enough generation to serve the load.
  *
  * What is checked and what is not is deliberate. Bus balance without Kirchhoff
  * voltage constraints is a '''relaxation''' of PyPSA's model, so the objective can
  * only come out lower — that inequality is asserted and must hold. Equality is
  * not: every line rating binds exactly here, because capacity was sized from the
  * expansion optimum, so the relaxation actively relieves tight limits rather
  * than merely reshuffling equally-priced flows. The objective lands 4.4e-06 low
  * and dispatch shifts by a couple of MW.
  *
  * Those gaps are bounded rather than tolerated: they are the numbers the cycle
  * constraints have to drive to zero. The line-flow test asserts the
  * disagreement still exists, so it fails when that lands — which is the signal
  * to replace it with a positive comparison.
  */
class LopfSuite extends munit.FunSuite:

  private def goldens: Path =
    Paths.get(sys.env.getOrElse("NOAIDI_GOLDENS", "reference/goldens"))

  private lazy val available: Boolean = Files.exists(goldens.resolve("schema.json"))
  private lazy val schema: Schema     = Schema.fromFile(goldens.resolve("schema.json"))

  private def network(name: String): Network =
    CsvReader.read(goldens.resolve("networks").resolve(name), schema, name)

  private def results(name: String): ujson.Value =
    ujson.read(Files.readString(goldens.resolve("results").resolve(s"$name.json")))

  private val params = PdhgParams(epsAbs = 1e-9, epsRel = 1e-9, maxIterations = 500_000)

  /** A column of a golden frame, by entity name, with tagged NaN handled. */
  private def frameValue(frame: ujson.Value, row: Int, column: String): Double =
    val index = frame("columns").arr.indexWhere(_.str == column)
    assert(index >= 0, s"golden frame has no column '$column'")
    frame("values")(row)(index) match
      case ujson.Num(v) => v
      case o: ujson.Obj if o.value.contains("$nan") => Double.NaN
      case other => fail(s"unexpected golden value $other")

  test("the objective is a lower bound on PyPSA's, as a relaxation must be") {
    assume(available, "goldens missing — run reference/generate_goldens.py")
    val expected = results("ac-dc-dispatch")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val result = Lopf.solve(network("ac-dc-dispatch"), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    // Bus balance without Kirchhoff voltage constraints is a '''relaxation''' of
    // PyPSA's model: it admits flow patterns no set of bus angles could produce,
    // so its optimum can only be lower. That inequality is the strong statement
    // available today and it must hold -- an objective above PyPSA's would mean a
    // constraint that should not be there, or a cost error.
    val target = expected("objective").num
    assert(
      result.objective <= target + 1e-6 * math.abs(target),
      f"objective ${result.objective}%.6f exceeds PyPSA's $target%.6f; a relaxation cannot cost more",
    )

    // And the gap is bounded, so a regression widening it would show. This is the
    // number the cycle constraints have to drive to zero, not a tolerance.
    val gap = (target - result.objective) / math.abs(target)
    assert(gap <= 1e-5, f"relaxation gap $gap%.3e is wider than the documented 4.4e-06")
  }

  test("generator dispatch is close to PyPSA's but not yet equal") {
    assume(available, "goldens missing")
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("generator_p")
    val result   = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal)

    // Every line rating binds in this fixture -- capacity was sized from the
    // expansion optimum, so s_nom equals the flow it was built to carry -- which
    // makes it the hardest case for a model without Kirchhoff constraints. The
    // relaxation redistributes flow around a cycle to relieve a tight limit and
    // shifts dispatch by a couple of MW doing so.
    //
    // Bounded rather than exact; exact agreement is what the cycle constraints
    // buy.
    val worst = n.snapshots.indices.flatMap { t =>
      n.require("Generator").ids.map { g =>
        math.abs(result.dispatch("Generator", g, t) - frameValue(expected, t, g))
      }
    }.max
    assert(worst <= 5.0, f"worst dispatch disagreement $worst%.3f MW exceeds the documented 5 MW")
  }

  test("total generation matches total load at every snapshot") {
    assume(available, "goldens missing")
    // The invariant bus balance exists to enforce, checked globally so a sign
    // error that cancels within one bus still shows up.
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val loads  = n.require("Load")

    n.snapshots.indices.foreach { t =>
      val generated = n.require("Generator").ids.map(result.dispatch("Generator", _, t)).sum
      val demanded  = loads.ids.map(loads.valueAt("p_set", _, t)).sum
      // Links convert with an efficiency, so the two sides differ by conversion
      // loss; ac-dc-dispatch's links are lossless, which this relies on.
      assertEqualsDouble(generated, demanded, 1e-3, s"snapshot $t")
    }
  }

  test("line flows stay within their ratings") {
    assume(available, "goldens missing")
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val lines  = n.require("Line")

    n.snapshots.indices.foreach { t =>
      lines.ids.foreach { l =>
        val flow = result.dispatch("Line", l, t)
        val rating = lines.float("s_nom", l)
        assert(
          math.abs(flow) <= rating + 1e-6,
          s"snapshot $t, line $l: flow $flow exceeds rating $rating",
        )
      }
    }
  }

  test("individual line flows do NOT yet match PyPSA") {
    assume(available, "goldens missing")
    // A known limitation, asserted so it cannot quietly become untrue. Without
    // Kirchhoff voltage constraints the flow pattern around a cycle is
    // underdetermined: bus balance alone admits many optimal patterns and the
    // solver picks one.
    //
    // In this fixture that also moves the objective, which is worth stating
    // plainly: every line rating binds exactly, because capacity was sized from
    // the expansion optimum. The relaxation is not merely choosing between
    // equally-priced flow patterns -- it relieves tight limits Kirchhoff would
    // enforce, and the objective comes out 4.4e-06 low.
    //
    // When the cycle constraints land this test should fail, and that failure is
    // the signal to replace it with a positive comparison.
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("line_p0")
    val result   = Lopf.solve(n, params)

    val disagreements = n.require("Line").ids.count { l =>
      val mine   = result.dispatch("Line", l, 0)
      val theirs = frameValue(expected, 0, l)
      math.abs(mine - theirs) > 1e-3
    }
    assert(
      disagreements > 0,
      "line flows now match PyPSA — Kirchhoff constraints appear to be in effect, " +
        "so replace this test with a positive comparison against line_p0",
    )
  }

  test("a capacity expansion network is rejected rather than mis-solved") {
    assume(available, "goldens missing")
    // The stock ac-dc-meshed is extendable. Solving it as dispatch would answer a
    // different question and silently produce a plausible number.
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(network("ac-dc-meshed"), params))
    assert(failure.getMessage.contains("extendable"), failure.getMessage)
  }

  test("a network with storage is rejected") {
    assume(available, "goldens missing")
    // storage-hvdc carries StorageUnits, whose energy balance couples
    // consecutive snapshots — dispatch alone cannot represent that.
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(network("storage-hvdc"), params))
    assert(
      failure.getMessage.contains("StorageUnit") || failure.getMessage.contains("extendable"),
      failure.getMessage,
    )
  }

  test("marginal prices are recovered at every bus") {
    assume(available, "goldens missing")
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)

    // Not yet compared against PyPSA's bus_marginal_price: nodal prices depend
    // on which optimal flow pattern the solver landed on, and that is
    // underdetermined until Kirchhoff constraints exist. What is asserted here is
    // that a price is produced and is finite for every bus — the dual side is
    // wired through, which is the part that could silently be NaN.
    n.require("Bus").ids.foreach { bus =>
      n.snapshots.indices.foreach { t =>
        val price = result.marginalPrice(bus, t)
        assert(price.isFinite, s"bus $bus at snapshot $t has price $price")
      }
    }
  }
