package org.noaidi.lopf

import java.nio.file.{Files, Path, Paths}
import scala.jdk.CollectionConverters.*
import org.noaidi.network.{CsvReader, Network, Schema, Topology}
import org.noaidi.prima.{PdhgParams, SolveStatus}

/** Dispatch against PyPSA's own optimisation results.
  *
  * The target is `ac-dc-dispatch`, generated by solving the stock
  * `ac-dc-meshed` expansion problem and then fixing capacity at its optimum.
  * The stock example cannot be used directly: it is a capacity expansion
  * problem, so its objective is negative with a large `objective_constant`, and
  * fixing capacity at the *given* `p_nom` instead is infeasible — there is not
  * enough generation to serve the load.
  *
  * Objective, generator dispatch and line flows match PyPSA exactly. Nodal
  * prices match at 4 of 10 snapshots and are legitimately '''different''' at the
  * rest, which took some work to establish rather than assume:
  *
  *   - Fixing capacity at the expansion optimum makes the instance severely
  *     degenerate. Every line rating binds exactly, and at six snapshots every
  *     generator sits precisely at a bound with total output equal to total load
  *     — so there is no marginal generator and nothing pins the price.
  *   - Tightening the solver from 1e-9 to 1e-12 moves the price gap by exactly
  *     zero (3.874938 either way, with a dual residual of 0.0), which rules out
  *     non-convergence: this is a different vertex of the same optimal dual face,
  *     not an unfinished one.
  *   - Part of that freedom is the CO2 multiplier. The cap is tight here but
  *     weakly binding, so any multiplier in a range is optimal; PyPSA's simplex
  *     reports 0 and a first-order method lands near -0.99. Since gas emits
  *     0.24/0.35 per MWh that shifts every gas-attached bus price by 0.678 —
  *     exactly the residual observed at snapshot 9.
  *
  * So what is asserted of the dual is that it is '''valid''' — strong duality —
  * plus the one part of it that is forced rather than chosen: a generator
  * strictly inside its bounds pins its bus price in every optimal dual, by
  * complementary slackness. That check is independent of PyPSA and fails on a
  * real dual error, which asserting equality with one particular vertex would
  * not.
  *
  * `ac-dc-co2` exists because `ac-dc-dispatch` cannot test the CO2 constraint at
  * all: omitting it entirely reproduces that fixture's objective exactly. See
  * `ac_dc_co2` in the generator for why, and what had to change to make a cap
  * that bites.
  */
class LopfSuite extends munit.FunSuite:

  private def goldens: Path =
    Paths.get(sys.env.getOrElse("NOAIDI_GOLDENS", "reference/goldens"))

  private lazy val available: Boolean = Files.exists(goldens.resolve("schema.json"))
  private lazy val schema: Schema     = Schema.fromFile(goldens.resolve("schema.json"))

  private def network(name: String): Network =
    CsvReader.read(goldens.resolve("networks").resolve(name), schema, name)

  private def results(name: String): ujson.Value =
    ujson.read(Files.readString(goldens.resolve("results").resolve(s"$name.json")))

  private val params = PdhgParams(epsAbs = 1e-9, epsRel = 1e-9, maxIterations = 500_000)

  private val temporaries = scala.collection.mutable.ArrayBuffer.empty[Path]

  /** A copy of a golden network with one file rewritten.
    *
    * Routed through `CsvReader` rather than assembled in memory on purpose: a
    * hand-built table can express states the reader never produces, so a test
    * built that way can pass while the real path stays broken.
    */
  private def copyOf(name: String): Path =
    val dir = Files.createTempDirectory("noaidi-lopf-")
    temporaries += dir
    val source = goldens.resolve("networks").resolve(name)
    // Closed explicitly: `Files.list` is backed by an open directory handle, and
    // this runs once per mutation test.
    scala.util.Using.resource(Files.list(source)) { entries =>
      entries.iterator.asScala.foreach(f => Files.copy(f, dir.resolve(f.getFileName.toString)))
    }
    dir

  private def mutate(name: String, file: String, edit: String => String): Network =
    val dir    = copyOf(name)
    val target = dir.resolve(file)
    val before = Files.readString(target)
    val after  = edit(before)
    // Otherwise a fixture that silently stops matching turns into a test that
    // asserts something about an unmodified network.
    assertNotEquals(after, before, s"the edit to $file changed nothing")
    Files.writeString(target, after)
    CsvReader.read(dir, schema, name)

  private def withExtraFile(name: String, file: String, content: String): Network =
    val dir = copyOf(name)
    Files.writeString(dir.resolve(file), content)
    CsvReader.read(dir, schema, name)

  override def afterAll(): Unit =
    temporaries.foreach { dir =>
      if Files.exists(dir) then
        scala.util.Using.resource(Files.walk(dir)) { paths =>
          paths.sorted(java.util.Comparator.reverseOrder).forEach(Files.delete)
        }
    }

  /** A column of a golden frame, by entity name, with tagged NaN handled. */
  private def frameValue(frame: ujson.Value, row: Int, column: String): Double =
    val index = frame("columns").arr.indexWhere(_.str == column)
    assert(index >= 0, s"golden frame has no column '$column'")
    frame("values")(row)(index) match
      case ujson.Num(v) => v
      case o: ujson.Obj if o.value.contains("$nan") => Double.NaN
      case other => fail(s"unexpected golden value $other")

  test("the objective matches PyPSA's") {
    assume(available, "goldens missing — run reference/generate_goldens.py")
    val expected = results("ac-dc-dispatch")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val result = Lopf.solve(network("ac-dc-dispatch"), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(
      result.objective,
      target,
      1e-6 * math.max(1.0, math.abs(target)),
      s"objective ${result.objective} against PyPSA's $target",
    )
  }

  test("generator dispatch matches PyPSA's") {
    assume(available, "goldens missing")
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("generator_p")
    val result   = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal)

    // Absolute, in MW: an idle generator sits at zero and a relative tolerance
    // would mean nothing there.
    n.snapshots.indices.foreach { t =>
      n.require("Generator").ids.foreach { g =>
        assertEqualsDouble(
          result.dispatch("Generator", g, t),
          frameValue(expected, t, g),
          1e-3,
          s"snapshot $t, generator $g",
        )
      }
    }
  }

  test("total generation matches total load at every snapshot") {
    assume(available, "goldens missing")
    // The invariant bus balance exists to enforce, checked globally so a sign
    // error that cancels within one bus still shows up.
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val loads  = n.require("Load")

    n.snapshots.indices.foreach { t =>
      val generated = n.require("Generator").ids.map(result.dispatch("Generator", _, t)).sum
      val demanded  = loads.ids.map(loads.valueAt("p_set", _, t)).sum
      // Links convert with an efficiency, so the two sides differ by conversion
      // loss; ac-dc-dispatch's links are lossless, which this relies on.
      assertEqualsDouble(generated, demanded, 1e-3, s"snapshot $t")
    }
  }

  test("line flows stay within their ratings") {
    assume(available, "goldens missing")
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    val lines  = n.require("Line")

    n.snapshots.indices.foreach { t =>
      lines.ids.foreach { l =>
        val flow = result.dispatch("Line", l, t)
        val rating = lines.float("s_nom", l)
        assert(
          math.abs(flow) <= rating + 1e-6,
          s"snapshot $t, line $l: flow $flow exceeds rating $rating",
        )
      }
    }
  }

  test("line flows match PyPSA's") {
    assume(available, "goldens missing")
    // This is what the cycle constraints buy. Bus balance alone leaves the flow
    // pattern around a cycle underdetermined, so before they existed this test
    // asserted the *disagreement* — and its failure was the signal to write this.
    val n        = network("ac-dc-dispatch")
    val expected = results("ac-dc-dispatch")("optimize")("line_p0")
    val result   = Lopf.solve(n, params)

    n.snapshots.indices.foreach { t =>
      n.require("Line").ids.foreach { l =>
        assertEqualsDouble(
          result.dispatch("Line", l, t),
          frameValue(expected, t, l),
          1e-3,
          s"snapshot $t, line $l",
        )
      }
    }
  }

  test("the cycle basis has the circuit rank of the passive graph") {
    assume(available, "goldens missing")
    // edges - nodes + components, counted over passive branches only. The
    // reference network is two triangles plus a lone pair, so two cycles.
    val n      = network("ac-dc-dispatch")
    val cycles = Cycles.basis(n)
    val edges  = Topology.passiveBranches(n).size
    val nodes  = n.require("Bus").ids.count(b => Topology.passiveBranches(n).exists((a, c) => a == b || c == b))
    val comps  = Topology.subNetworks(n).count(_.size > 1)
    assertEquals(cycles.size, edges - nodes + comps, s"cycles=${cycles.map(_.terms)}")
    assertEquals(cycles.size, 2)
  }

  test("a capacity expansion network is rejected rather than mis-solved") {
    assume(available, "goldens missing")
    // The stock ac-dc-meshed is extendable. Solving it as dispatch would answer a
    // different question and silently produce a plausible number.
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(network("ac-dc-meshed"), params))
    assert(failure.getMessage.contains("extendable"), failure.getMessage)
  }

  test("a network with storage is rejected") {
    assume(available, "goldens missing")
    // storage-hvdc carries StorageUnits, whose energy balance couples
    // consecutive snapshots — dispatch alone cannot represent that.
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(network("storage-hvdc"), params))
    assert(
      failure.getMessage.contains("StorageUnit") || failure.getMessage.contains("extendable"),
      failure.getMessage,
    )
  }

  test("the dual solution is optimal, though not the same one PyPSA reports") {
    assume(available, "goldens missing")
    // Prices come off the balance-constraint duals through RowTranslation. The
    // primal matches PyPSA exactly -- objective, dispatch and flows -- so the
    // dual question is only *which* optimal dual, and on this fixture that is not
    // unique.
    //
    // The instance is deliberately degenerate: capacity was sized from the
    // expansion optimum, so every line rating binds exactly, and every gas
    // generator sits at its zero lower bound. Far more constraints are active at
    // the optimum than there are variables, which makes the optimal dual a face
    // rather than a point. PyPSA's simplex reports a vertex of it (prices equal
    // to the marginal wind costs); a first-order method converges to a different
    // point of the same face.
    //
    // So what is asserted here is strong duality -- the two objectives agreeing
    // is what makes both the primal and the dual optimal rather than merely
    // feasible -- plus finiteness of every price. The part of the dual that is
    // *forced* rather than chosen is asserted separately, in "a generator
    // strictly inside its bounds pins its bus price"; between them those two
    // cover what any optimal dual must satisfy. Asserting equality with PyPSA's
    // prices would be asserting a choice neither solver is obliged to make.
    val n      = network("ac-dc-dispatch")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal)

    // Strong duality: the two objectives agreeing is what makes both the primal
    // and the dual optimal rather than merely feasible.
    assertEqualsDouble(
      result.solution.objectiveValue,
      result.solution.dualObjectiveValue,
      1e-6 * math.max(1.0, math.abs(result.objective)),
      s"strong duality violated: ${result.solution.kkt}",
    )

    // And every price is a finite number, so the dual path cannot silently be
    // NaN -- which is the failure that would otherwise hide behind a tolerance.
    n.require("Bus").ids.foreach { bus =>
      n.snapshots.indices.foreach { t =>
        assert(result.marginalPrice(bus, t).isFinite, s"bus $bus at snapshot $t")
      }
    }
  }

  test("the objective matches PyPSA's when a CO2 cap binds") {
    assume(available, "goldens missing")
    // ac-dc-co2 prices gas below wind so the cap displaces generation it would
    // otherwise be economic to run. Ignoring the constraint gives 2819.52 against
    // this 3178.55, so unlike ac-dc-dispatch this fixture can tell an
    // implementation of the constraint apart from its absence.
    val expected = results("ac-dc-co2")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val result = Lopf.solve(network("ac-dc-co2"), params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * math.abs(target), s"against PyPSA's $target")

    // And PyPSA agrees the cap is doing work, so this is not a fixture that
    // happens to be satisfied for some other reason.
    assertNotEquals(expected("global_constraint_mu")("co2_limit").num, 0.0)
  }

  test("the CO2 cap is respected and reached") {
    assume(available, "goldens missing")
    // Both halves matter. Emissions above the cap mean the row is absent or
    // mis-signed; emissions well *under* it would mean the row is over-tight, and
    // the objective comparison alone cannot separate those from a coefficient
    // error that happens to land on the same cost.
    val n        = network("ac-dc-co2")
    val result   = Lopf.solve(n, params)
    val gens     = n.require("Generator")
    val carriers = n.require("Carrier")

    val emitted = n.snapshots.indices.map { t =>
      gens.ids.map { g =>
        val intensity = carriers.float("co2_emissions", gens.string("carrier", g))
        // The `generators` weighting, which is what PyPSA scales emissions by --
        // not `objective`, which scales cost. Reading the same column the builder
        // reads would make this agree with the implementation rather than check
        // it, so it is named here independently.
        result.dispatch("Generator", g, t) * intensity / gens.valueAt("efficiency", g, t) *
          n.weighting("generators", t)
      }.sum
    }.sum

    val cap = n.require("GlobalConstraint").float("constant", "co2_limit")
    assert(emitted <= cap + 1e-3, s"emitted $emitted exceeds cap $cap")
    // Unconstrained this network emits 6702, so landing on the cap is the
    // constraint binding rather than an accident of the dispatch.
    assertEqualsDouble(emitted, cap, 1e-2, s"emitted $emitted against cap $cap")
  }

  test("a generator strictly inside its bounds pins its bus price") {
    assume(available, "goldens missing")
    // The part of the dual that is forced rather than chosen. Complementary
    // slackness makes an interior variable's reduced cost zero in *every* optimal
    // dual, so for a zero-emission generator — where the CO2 term vanishes and no
    // other row touches it — the bus price equals its marginal cost exactly.
    // Unlike a comparison against PyPSA's vertex this cannot be failed by a
    // legitimate alternative optimum, and it is what actually separates a dual bug
    // from degeneracy on this fixture: it is how snapshot 9 was identified as the
    // former while 6 and 8 were the latter.
    val n        = network("ac-dc-dispatch")
    val result   = Lopf.solve(n, params)
    val gens     = n.require("Generator")
    val carriers = n.require("Carrier")
    var checked  = 0

    n.snapshots.indices.foreach { t =>
      gens.ids.foreach { g =>
        val pNom  = gens.float("p_nom", g)
        val lo    = pNom * gens.valueAt("p_min_pu", g, t)
        val hi    = pNom * gens.valueAt("p_max_pu", g, t)
        val p     = result.dispatch("Generator", g, t)
        val clean = carriers.float("co2_emissions", gens.string("carrier", g)) == 0.0
        // A margin well above the solver tolerance, so "interior" is not a
        // rounding artefact of a variable resting on its bound.
        if clean && p > lo + 1e-2 && p < hi - 1e-2 then
          checked += 1
          assertEqualsDouble(
            result.marginalPrice(gens.string("bus", g), t),
            gens.valueAt("marginal_cost", g, t),
            1e-3,
            s"snapshot $t, interior generator $g",
          )
      }
    }
    // Otherwise the test passes by finding nothing to check.
    assert(checked >= 2, s"only $checked interior generator(s) found; the check is vacuous")
  }

  test("a component attached to a nonexistent bus is rejected") {
    assume(available, "goldens missing")
    // Not hypothetical: a load whose bus is stale simply vanishes from the balance
    // rows, and the LP stays feasible and returns a *cheaper* answer with no
    // diagnostic. Cheaper-and-silent is the worst direction for an error to go.
    val broken  = mutate("ac-dc-dispatch", "loads.csv", _.replace(",Manchester,", ",Mancester,"))
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(broken, params))
    assert(failure.getMessage.contains("Mancester"), failure.getMessage)
  }

  test("an unmodelled component is rejected rather than dropped") {
    assume(available, "goldens missing")
    // A ShuntImpedance draws real power and is not built here. Dropping it leaves
    // a feasible LP describing a different network, so it has to be refused — the
    // same reason extendable capacity and storage are.
    val broken = withExtraFile(
      "ac-dc-dispatch",
      "shunt_impedances.csv",
      "name,bus,g,b\nshunt,Manchester,0.1,0.0\n",
    )
    val failure = intercept[Lopf.UnsupportedNetwork](Lopf.solve(broken, params))
    assert(failure.getMessage.contains("ShuntImpedance"), failure.getMessage)
  }

  // A test asserting that prices lie between the cheapest and dearest marginal
  // cost was written here and removed: the claim is false. With a binding
  // transmission limit, serving one more MW at a bus can require raising
  // expensive generation at one end while backing off cheap generation at the
  // other, and the resulting nodal price legitimately exceeds every generator's
  // cost. Congestion rent is a feature of locational pricing, not a symptom. The
  // observed 6.80 against a dearest cost of 5.89 is within that.
  //
  // What remains open is the gap against PyPSA, recorded in NOTES rather than
  // papered over with a tolerance.

  test("a cycle spanning transformers matches PyPSA's dispatch") {
    assume(available, "goldens missing")
    // The LOPF half of the transformer conversion. `Cycles.impedance` refers a
    // transformer to `s_nom` and `tap_ratio` where a line goes to `v_nom^2`, and
    // this fixture has a cycle crossing two transformers so the choice changes
    // the flows -- in a radial network topology would fix them and any base would
    // do.
    val expected = results("transformer-levels")("optimize")
    assert(!expected.obj.contains("error"), s"golden solve failed: ${expected.obj.get("error")}")

    val n      = network("transformer-levels")
    val result = Lopf.solve(n, params)
    assertEquals(result.status, SolveStatus.Optimal, s"${result.solution}")

    val target = expected("objective").num
    assertEqualsDouble(result.objective, target, 1e-6 * target, s"against PyPSA's $target")

    val flows = expected("transformer_p0")
    n.snapshots.indices.foreach { t =>
      n.require("Transformer").ids.foreach { id =>
        assertEqualsDouble(
          result.dispatch("Transformer", id, t),
          frameValue(flows, t, id),
          1e-3,
          s"snapshot $t, transformer $id",
        )
      }
    }
  }
